[WIP]ナレッジ投稿機能の実装
tc-tokyo-developers/tech-lead pull request #11
Opened 2018-01-12 11:56 UTC by k-kohey

ref <https://github.com/tc-tokyo-developers/dev-issues/issues/7>

# WHAT
メンターがナレッジを投稿と閲覧, 受講生が閲覧できる機能を実装する.
ナレッジの記述にはマークダウンを使用する.

- [ ] ナレッジ投稿機能
- [ ] 投稿する際のリアルタイムプレビュー機能
- [ ] メイン画面にナレッジ一覧を表示
- [ ]  ナレッジ一覧の表示画面では、gem(redcarpetが良さそう)を利用してmarkdownをパースする
- [ ] ナレッジ一覧のページネーション実装
- [ ] ナレッジ一覧からナレッジを押したらナレッジの詳細画面に飛ぶようにする
- [ ] ナレッジの詳細画面に、メンターであれば編集画面に飛ぶリンクを設置する
- [ ] markdownをパース(投稿、表示の両方)するときはsyntax highlightが効くようにする(重要度低め)
- [ ] モデルのvalidation
- [ ] テストを書けているか

# WHY
メンターと受講生の間で知識の共有をするため.

## チェック項目

1. 実装したい機能が実装できているか
2. テストコードを正しく書けているか
3. n+1問題が発生していないか(bulletで確認)
4. rubocopに怒られてないか
5. ヘルパー等作成した場合、命名と処理の内容が適切か
6. ネストが多いとか読みにくいコードになってないか

2018-01-13 06:58 UTC, k-kohey commented
update branchしました

2018-01-13 08:22 UTC, k-kohey commented
ナレッジ一覧の表示画面でマークダウンをパースして表示 とのことですが, これは現在top controller で表示しているナレッジ一覧とは別に用意するという事でしょうか??

2018-01-13 08:53 UTC, ebkn12 commented
@k-kohey knowledge#showで表示した際にパースして表示するイメージです。

いまknowledgesコントローラーを作成してますが、
`mentor/knowledges_controller`と`student/knowledges_controller`を作成してください。

mentor側にはindex, show, new, create, edit, update, destroyアクション
student側にはindex, showアクション

を作成するイメージです。

***

それと、gitignoreに.idea追加したのに消えてないみたいです。 `git rebase -i`を使ってコミット削除してみてください

2018-01-13 12:44 UTC, k-kohey commented
忘れないように メモ
https://marvelapp.com/adj7e6j/screen/34717721

2018-01-14 03:43 UTC, ebkn12 commented on app/controllers/knowledge_controller.rb
> +end
knowledgesControllerはいらないですよー

2018-01-14 03:44 UTC, ebkn commented on db/migrate/20180113070013_create_knowledges.rb
> +      t.references :user, foreign_key: true
これだと`NOT NULL`制約かかってないんで、`null: false`もつけてください

2018-01-14 03:45 UTC, ebkn commented on db/migrate/20180113070013_create_knowledges.rb
> +  end
endが足りない気が、、？

2018-01-14 03:45 UTC, ebkn commented on app/controllers/student/knowledges_controller_controller.rb
> +class Student::KnowledgesControllerController < ApplicationController
controllercontrollerになっちゃってます

2018-01-15 02:38 UTC, ebkn requested changes

2018-01-15 02:38 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +  def strong_params
knowledgeに関するstrong parameterは`knowledge_params`にしましょう
これはrailsの習慣的なやつですね

あとprivateにしてください

2018-01-15 02:38 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +class Mentor::KnowledgesController < Mentor::BaseController
👍

2018-01-15 02:38 UTC, ebkn12 commented on app/views/mentor/knowledges/new.html.haml
> +  %input{type: "submit", value: "SENT"}
formはできるだけform_forとformヘルパー使って書いてください

2018-01-15 02:38 UTC, ebkn12 commented on config/routes.rb
> +    resource :knowledges
indexがあるので`resources`では？
`resource`と`resources`は違いますよ

2018-01-15 02:38 UTC, ebkn12 commented on db/migrate/20180114091057_change_constraint_user_id_of_knowledges.rb
> +    change_column_null :knowledges, :user_id, false
これで`NOT NULL`制約つけてもいいですが、migrationファイルがどんどん増えていくことに繋がるので、
既にデータがたくさん入っていて修正が厳しい
とかでなければrollbackしてmigrationファイル書き直したほうがいいです

2018-01-15 02:38 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +  end
メソッドは
```ruby
def index
  # 処理
end

def show; end

def create
　# 処理
end
```
のようなインデント(改行)にしましょう

rubocopに怒られると思います

2018-01-15 02:39 UTC, ebkn12 commented
@k-kohey SideCIがrubocopとかちぇっくしてくれるので、落ちたら見るようにしてみるといいと思います！
https://sideci.com/gh/111798438/pull_requests/11

2018-01-15 11:12 UTC, k-kohey commented on db/migrate/20180114091057_change_constraint_user_id_of_knowledges.rb
> +    change_column_null :knowledges, :user_id, false
なるほど... 次回からそうします!!

2018-01-15 12:54 UTC, k-kohey commented
怒られてるところは, 後日直したいと思います(すいません).
jsでいい感じにプレビューする方法を調べ&考え中です.

2018-01-15 14:26 UTC, ebkn requested changes
細かいですがコメントしました。

helperみたいに素のrubyのコードを書く時は特に、どんなコードが一番わかり易いか考えながらやると良いと思います 👍

2018-01-15 14:26 UTC, ebkn12 commented on Gemfile
> +gem 'redcarpet'
個人的にはdotenv-railsの下あたりに書いてほしいです

```
全体で使うgem

環境別で使うgem

(windows対応)
```

2018-01-15 14:26 UTC, ebkn12 commented on app/helpers/markdown_helper.rb
> +end
最後には改行を入れるようにしてください
確かgcc(C言語のコンパイラ)関係でエラーが出るみたいです

2018-01-15 14:26 UTC, ebkn12 commented on app/helpers/markdown_helper.rb
> +  end
返しているのがパースした結果なので、メソッド名は`parse(text)`とかにすると良さそう(ぱっと思いついただけなので考えてみてください)

こんな感じに書くとrubyっぽいです
```ruby
def parse(text)
  markdown.render(text).html_safe
end

private

def renderer
  @renderer ||= Redcarpet::Render::HTML.new
end

def markdown
  @markdown ||= Redcarpet::Markdown.new(renderer)
end
```

2018-01-15 14:26 UTC, ebkn12 commented on app/views/mentor/knowledges/new.html.haml
> += form_for ['knowledge', @knowledge], url: '/mentor/knowledges' do |f|
`'mentor', @knowledge`だとだめですか？
form_forなのにurlオプションつけるのは微妙な気がします

2018-01-15 14:26 UTC, ebkn12 commented on db/migrate/20180114091057_change_constraint_user_id_of_knowledges.rb
> +    change_column_null :knowledges, :user_id, false
あ、今回も修正してください 🙏

2018-01-15 14:26 UTC, ebkn12 commented on app/views/mentor/knowledges/new.html.haml
> +  = f.text_area :content, colos: "100", row: "100"
`cols`の間違い?

2018-01-15 14:26 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +  def knowledge_params
privateとdefの間はあけるのがrubocop式です

2018-01-15 14:26 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +    params.require(:knowledge).permit(:title, :content).merge(user_id: current_mentor.id)
```ruby
params.require(:knowledge)
      .permit(:title, :content)
      .merge(user_id: current_mentor.id)
```

みたいに揃えるときれいに見えますね

2018-01-15 17:47 UTC, k-kohey commented on app/views/mentor/knowledges/new.html.haml
> += form_for ['knowledge', @knowledge], url: '/mentor/knowledges' do |f|
form_for ['x', y] のxってどういう意味なんですか???

2018-01-16 05:50 UTC, ebkn12 commented on app/views/mentor/knowledges/new.html.haml
> += form_for ['knowledge', @knowledge], url: '/mentor/knowledges' do |f|
namespaceですね

2018-01-19 05:22 UTC, ebkn12 commented on app/views/mentor/knowledges/new.html.haml
> +  = f.text_area :content, cols: "100", row: "100"
__[HAML-Lint]__

Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-19 05:22 UTC, ebkn12 commented on app/views/mentor/knowledges/new.html.haml
> +%div{id: "preview"}
__[HAML-Lint]__

Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-19 05:22 UTC, ebkn12 commented on app/views/mentor/knowledges/new.html.haml
> +%div{id: "preview"}
__[HAML-Lint]__

Hash attribute should start with one space after the opening brace


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-19 05:22 UTC, ebkn12 commented on app/views/student/knowledges/index.html.haml
> +    = link_to "#{knowledge.title}", mentor_knowledge_path(knowledge)
__[HAML-Lint]__

Files should end with a trailing newline


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-19 05:22 UTC, ebkn12 commented on app/views/student/knowledges/index.html.haml
> +    = link_to "#{knowledge.title}", mentor_knowledge_path(knowledge)
__[HAML-Lint]__

Style/UnneededInterpolation: Prefer `to_s` over string interpolation.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-19 05:22 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +        .permit(:title, :content)
__[RuboCop]__

Layout/MultilineMethodCallIndentation: Align `.permit` with `.require` on line 35.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-19 05:22 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +        .merge(user_id: current_mentor.id)
__[RuboCop]__

Layout/MultilineMethodCallIndentation: Align `.merge` with `.require` on line 35.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-19 05:22 UTC, ebkn12 commented on app/controllers/student/knowledges_controller.rb
> +
__[RuboCop]__

Layout/EmptyLinesAroundClassBody: Extra empty line detected at class body end.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-19 05:22 UTC, ebkn12 commented on app/helpers/markdown_helper.rb
> +    markdown.render(text).html_safe
__[RuboCop]__

Rails/OutputSafety: Tagging a string as html safe may be a security risk.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-19 05:24 UTC, k-kohey commented
すいません! あんまし進んで無いんですが, リアルタイムプレビューを下記サイトを参考に作っていきたいと思います

https://qiita.com/erb_owl/items/907b76c6f2699ee1748f#%E8%A7%A3%E8%AA%AC

2018-01-19 06:22 UTC, ebkn requested changes

2018-01-19 06:22 UTC, ebkn12 commented on Gemfile
> +gem 'jquery-rails'
5.1系じゃないんで`jquery-rails`は入ってます(14行目)

2018-01-19 06:22 UTC, ebkn12 commented on app/controllers/student/knowledges_controller.rb
> +    @knowledges = Knowledge.order('id ASC')
`.order('id ASC')`って`.all`とどう違いますか？
同じだと思ってたんですが

2018-01-19 06:22 UTC, ebkn12 commented on app/views/mentor/accounts/edit.html.haml
> += link_to 'キャンセル', mentor_account_path
最後に改行入れるようにしてください
(rubymineなら設定できるはず)

2018-01-19 06:22 UTC, ebkn12 commented on app/views/mentor/knowledges/new.html.haml
> +  });
jsをhtmlに書くのは微妙ですね
asset_pipelineで管理させたいので、`assets/javascript/`以下に配置してください

2018-01-19 06:22 UTC, ebkn12 commented on app/views/mentor/knowledges/show.html.haml
> += parse(@knowledge.content)
ここだけ見ると、`parse`ってちょっとわかりにくい気がしました
`parse_markdown`とかの方がいいかも

2018-01-21 17:06 UTC, k-kohey commented
conflict起きててhub上でupdate branchが出来ないのですが, これはローカルの方を保持する感じで大丈夫ですか?
![2018-01-22 2 04 03](https://user-images.githubusercontent.com/26789330/35196673-ae4eab88-ff18-11e7-9f8e-8dedb95217e3.png)

2018-01-21 22:11 UTC, k-kohey commented on app/views/mentor/accounts/edit.html.haml
> += link_to 'キャンセル', mentor_account_path
設定しました!

2018-01-21 22:22 UTC, k-kohey commented on app/controllers/student/knowledges_controller.rb
> +    @knowledges = Knowledge.order('id ASC')
多分同じですね. わかりやすいのでallになおしておきました!!
一応sqlを確認しておきました. 何故か, allの方が遅くなっちゃてますが, 理論的には .order('id ASC') の方が遅くなりそうです.

![2018-01-22 7 16 50](https://user-images.githubusercontent.com/26789330/35199669-75c5581c-ff44-11e7-8be5-e62bb801afb7.png)

2018-01-22 01:54 UTC, ebkn12 commented
＠k-kohey masterの変更を組み込む形でお願いします

2018-01-22 01:57 UTC, ebkn12 commented on app/controllers/student/knowledges_controller.rb
> +    @knowledges = Knowledge.order('id ASC')
:+1: 
でもよく考えたらここってcreated_at descなんじゃないかなと

2018-01-26 03:30 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +    @knowledges = Knowledge.order("created_at desc")
__[RuboCop]__

Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-26 03:30 UTC, ebkn12 commented on app/controllers/student/knowledges_controller.rb
> +
__[RuboCop]__

Layout/TrailingBlankLines: 1 trailing blank lines detected.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-26 03:30 UTC, ebkn12 commented on app/views/mentor/knowledges/edit.html.haml
> +  = f.text_field :title, placeholder: "title"
__[HAML-Lint]__

Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-26 03:30 UTC, ebkn12 commented on app/views/mentor/knowledges/edit.html.haml
> +  = f.text_area :content, cols: "100", row: "100"
__[HAML-Lint]__

Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-26 04:03 UTC, k-kohey commented
RuntimeError: Unable to find a spec satisfying redcarpet (>= 0) in the set. Perhaps the lockfile is corrupted?

前回のupdate branch分の差分をpullった後から, 上記のエラーが rails bundleコマンドを行うと出てくるようになりました. gemfile.lockを削除すると解決することを確認したのですが, それを消去すると, これからのチーム開発に支障が出ますか?

2018-01-26 04:10 UTC, ebkn12 commented
@k-kohey `bundle update redcarpet`でいけないですか？
masterとの差分が`redcarpet`に関するgemfile/gemfile.lockになるようにしてください

2018-01-26 04:25 UTC, k-kohey commented
以下のような感じで怒られましたが, 以前誤って追加してjqueryのgemを消してbundle updateしたら直りました. 今回のエラーはどういう意味だったのでしょうか.

Could not find gem 'redcarpet'.

2018-01-26 08:19 UTC, ebkn12 commented
@k-kohey `update branch`してくださいね

2018-01-26 13:13 UTC, ebkn12 commented on app/views/mentor/knowledges/new.html.haml
> +  = f.submit 'ajax', id: "ajax"
__[HAML-Lint]__

Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-26 13:13 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +  private
__[RuboCop]__

Layout/EmptyLinesAroundAccessModifier: Keep a blank line before and after `private`.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-26 13:13 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +    markdown.render(params.require(:knowledge)[:content]).html_safe
__[RuboCop]__

Rails/OutputSafety: Tagging a string as html safe may be a security risk.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-27 02:41 UTC, ebkn requested changes

2018-01-27 02:41 UTC, ebkn12 commented on Gemfile
> +gem 'kaminari'
👍

2018-01-27 02:41 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +  skip_before_action :authenticate_mentor
`skip_before_action`はしないでください。
authenticateされていない人は見れちゃだめです

2018-01-27 02:41 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +    if params[:commit] == 'ajax'
paramsで判断するのは微妙ですね
ajaxかどうか判断するのには`respond_to`を使いましょう。アクションを分けるのもありです

2018-01-27 02:41 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +  end
他のところに似たようなコードがあった気が。
`render :text`じゃなくて、ビューに書けばいいのでは？
`render :ajax_response`として、view/mentor/knowledges/ajax_resopnse.html.hamlにしたら行ける気がする、、

2018-01-27 02:41 UTC, ebkn12 commented on app/models/knowledge.rb
> +  validates :id, presence: true, uniqueness: true
idのvalidationはしなくていいですよ
activerecordが自動で主キーとしていい感じにしてくれるので

2018-01-27 02:41 UTC, ebkn12 commented on app/views/mentor/knowledges/index.html.haml
> +    = link_to "#{knowledge.title}", mentor_knowledge_path(knowledge)
`"#{}"`は要らない気がします

2018-01-27 02:41 UTC, ebkn12 commented on app/views/mentor/knowledges/new.html.haml
> +  = f.submit 'ajax', id: 'ajax'
ajaxっていうid名は微妙ですね。一意に判別できるような名前にしてください

2018-01-29 00:54 UTC, k-kohey commented on app/controllers/mentor/knowledges_controller.rb
> +    if params[:commit] == 'ajax'
respond_to でajaxかどうかを判断する方法がネット見てもあまりピンとこないんですが, どんな感じでしょうか.  アドバイス頂きたいです...!

見たサイト
http://railsdoc.com/references/respond_to
https://qiita.com/mm36/items/684f36f22e79d0a27ae9

2018-01-29 03:34 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +    if params[:commit] == 'ajax'
ajaxかどうか、というよりかはリクエストされた形式に応じて場合分けするみたいなイメージが近いと思います。
jsonでリクエストしたらformat.jsonみたいな感じです。

controller内で`render json: {}`みたいに書いてもいいですし、viewにjbuilderファイル作ってレスポンスを書くとかでもいいです。

2018-01-31 08:42 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +  skip_before_action :authenticate_mentor, if: proc { current_mentor}
__[RuboCop]__

Layout/SpaceInsideBlockBraces: Space missing inside }.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-31 08:42 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +      redirect_to :action => "index"
__[RuboCop]__

Style/HashSyntax: Use the new Ruby 1.9 hash syntax.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-31 08:42 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +      redirect_to :action => "index"
__[RuboCop]__

Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-01-31 08:42 UTC, ebkn12 commented on app/helpers/markdown_helper.rb
> +
__[RuboCop]__

Layout/EmptyLinesAroundModuleBody: Extra empty line detected at module body beginning.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-02-01 01:57 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +  skip_before_action :authenticate_mentor, if: proc {current_mentor}
__[RuboCop]__

Layout/SpaceInsideBlockBraces: Space missing inside {.


<!-- Comment by [SideCI](https://sideci.com) -->

2018-02-01 02:02 UTC, k-kohey commented
すいません! 結局良くわからなくて, ajaxの判定をparamsでやってます.
ajaxのformを分けてレスポンスをjsonにして, コントローラーでパースしてjsonでviewに返すってかんじでやったらうまくいくのかなあとか思いながら試行錯誤してました.

2018-02-01 02:03 UTC, k-kohey commented
あと期限が過ぎているのに申し訳ないのですが, 2/7まで忙しくてあまりコミット出来なそうです.

2018-02-01 16:20 UTC, ebkn requested changes
レビュー遅れて申し訳ないです 🙏 
引き続きがんばってくださいー

その都度動作をgifで載せてくれたりすると助かりますね

2018-02-01 16:20 UTC, ebkn12 commented on Gemfile.lock
> +    uglifier (4.1.4)
uglifier、i18n、minitestは関係ないのでこのPRではバージョン上げないでください。
(ローカルのgemのバージョンを調整してやるのが良さそう)

2018-02-01 16:20 UTC, ebkn12 commented on app/assets/javascripts/new.js.erb
> +$(document).ready(function() {
たしかturbolinks消してないので、`$(document).on('turbolinks:load', funciton(){`で書いてください

後々turbolinks消すかもしれませんが、どうしても外さないと動作がおかしいという場合を除き、この記述のままだとブラウザをリロードして１発目にはjsが動かないと思います

2018-02-01 16:20 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +  skip_before_action :authenticate_mentor, if: proc {current_mentor}
`if: proc {current_mentor}` これどういう意図で書いてます？
ローカルのユーザー認証機能動いてないんですか？

2018-02-01 16:20 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +    if params[:commit] == 'ajax_params'
とりあえずOK。

2018-02-01 16:20 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +      render text: view_context.parse_markdown(params[:knowledge][:content])
render text:にするなら、viewに書きましょう。
そうすればview_helperも書けるので

2018-02-01 16:20 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +      Knowledge.create(knowledge_params)
```ruby
@knoledge = Knowledge.new(knowledge_params)
if params[:commit] == 'ajax_params'
  # 
else
  @knowledge.save
  redirect_to mentor_knowledges_path
end
```
こんな感じでどうでしょう？

2018-02-01 16:20 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +      redirect_to action: 'index'
action指定よりかはprefix使いましょう
今回は`mentor_knowledges_path`？

2018-02-01 16:20 UTC, ebkn12 commented on app/views/mentor/knowledges/new.html.haml
> +  = f.submit 'ajax_params', id: 'knowledge_create_ajax', format: 'json'
f.submitが２つあるのって見たことないんですがどういう挙動を？
手動で両方とも押せますよね

2018-02-01 16:20 UTC, ebkn12 commented on app/views/student/knowledges/index.html.haml
> += @knowledges.each do |knowledge|
テンプレートでできるだけeach文は使わず部分テンプレートに切り分けてください

viewにはできるだけロジックを書かないのが大事です

2018-02-10 17:45 UTC, k-kohey commented on app/controllers/mentor/knowledges_controller.rb
> +  skip_before_action :authenticate_mentor, if: proc {current_mentor}
理由は調べてないんですが, mentorがログインしていても認証画面にリダイレクトしまうので, それを避けるために記述しました.

2018-02-10 23:44 UTC, k-kohey commented on app/views/mentor/knowledges/new.html.haml
> +  = f.submit 'ajax_params', id: 'knowledge_create_ajax', format: 'json'
paramsをajaxで送られたかどうか判別するために, ajaxが押すsubmitとそうではないsubmitに分けました. 最終的にはcssで隠す予定です.

2018-02-12 13:40 UTC, ebkn12 commented on app/controllers/mentor/knowledges_controller.rb
> +  skip_before_action :authenticate_mentor, if: proc {current_mentor}
了解です。
マージする前に確認しましょう

2018-03-06 11:07 UTC, ebkn12 commented
時間できたときにやります

2018-08-13 05:45 UTC, closed without merging