[WIP] create pull request
tc-tokyo-developers/tech-lead pull request #2
Opened 2017-12-03 08:36 UTC by Ryosuke12323

ref https://github.com/tc-tokyo-developers/dev-issues/issues/4

# WHAT
実装する機能の概要
・メインのviewの作成
必要な機能(メインの機能、validation、例外処理等)の一覧

- [ ]
- [ ]

# WHY
この機能を実装する理由

***

*DBに何か変更を加えていれば記述する

*フロントに何か実装していればスクリーンショットを貼付する

***

## チェック項目

1. 実装したい機能が実装できているか
2. テストコードを正しく書けているか
3. n+1問題が発生していないか(bulletで確認)
4. rubocopに怒られてないか
5. ヘルパー等作成した場合、命名と処理の内容が適切か
6. ネストが多いとか読みにくいコードになってないか

2017-12-30 12:44 UTC, ebkn12 commented on Gemfile.lock
> +   1.16.0
https://qiita.com/suu_g/items/2b1630b8015d51c5292e

`bundle install --path vendor/bundle`をバージョンが異なるbundlerで実行すると起きる問題です。

今後は`1.16.0`を使っていくことにします。

2017-12-30 13:02 UTC, ebkn12 commented on Gemfile
> +# Github認証
僕のタイポです 🙏

2017-12-30 13:17 UTC, ebkn requested changes

2017-12-30 13:17 UTC, ebkn12 commented on app/assets/images/chat.svg
> +</svg>
このアイコン微妙なんであとで変更しましょう

2017-12-30 13:17 UTC, ebkn12 commented on app/assets/images/face2.svg
> +<svg fill="#000000" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
削除

2017-12-30 13:17 UTC, ebkn12 commented on app/assets/images/face.svg
> +<svg fill="#000000" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
アバター機能ができるまでの仮imageですね

2017-12-30 13:17 UTC, ebkn12 commented on app/assets/javascripts/application.js
> +//= require vendor/bootstrap-material-design
gem使わないでjsのライブラリを読み込むときはこの方法を使うので覚えておいてください！

2017-12-30 13:17 UTC, ebkn12 commented on app/assets/stylesheets/application.scss
> +// }
つかってないのは削除してください！

2017-12-30 13:17 UTC, ebkn12 commented on app/assets/stylesheets/partials/_base.scss
> +@import 'bootstrap-custom';
👍

2017-12-30 13:17 UTC, ebkn12 commented on app/assets/stylesheets/partials/_bootstrap-custom.scss
> +  display: inline;
`display: inline`って必要です？
もし必要なら、一番上に書くのが良いですね
影響力が大きいプロパティから順に書いていくのが良いです！

2017-12-30 13:17 UTC, ebkn12 commented on app/assets/stylesheets/partials/_bootstrap-custom.scss
> +  display: inline-block;
このあたりも

2017-12-30 13:17 UTC, ebkn12 commented on app/controllers/top_controller.rb
> +end
仮のcontrollerですね

2017-12-30 13:17 UTC, ebkn12 commented on app/views/layouts/application.html.haml
> +    %link{ rel: 'stylesheet', href: 'https://unpkg.com/bootstrap-material-design@4.0.0-beta.4/dist/css/bootstrap-material-design.min.css', integrity: 'sha384-R80DC0KVBO4GSTw+wZ5x2zn2pu4POSErBkf8/fSFh
bootstrap-material-design.cssがあるのでかぶってる気が

2017-12-30 13:17 UTC, ebkn12 commented on app/views/layouts/application.html.haml
> +    %title TECH::LEAD
修正ありがとうございます！

2017-12-30 13:17 UTC, ebkn12 commented on app/views/shered/_footer.html.haml
> +    %p.m-0.text-center.text-muted &copy; 2018 TECH::LEAD
Copyrightの書き方は覚えておきましょう！

2017-12-30 13:17 UTC, ebkn12 commented on spec/controllers/top_controller_spec.rb
> +end
仮のコントローラーなのでこのファイルは消しましょう

2017-12-30 13:17 UTC, ebkn12 commented on app/views/shered/_header.html.haml
> +        = # TODO url変更する
`TODO`書いていてありがたいです

2017-12-30 13:17 UTC, ebkn12 commented on app/views/top/index.html.haml
> +  - 20.times do
ここもTODO書いておいてください

2017-12-30 13:17 UTC, ebkn12 commented on config/routes.rb
> +  root "top#index"
ここはシングルクオーテーションで書くべきですが仮のやつなのでOKです

2017-12-30 13:17 UTC, ebkn12 commented on app/views/top/index.html.haml
> +          %img.rounded-circle{ width: '35px;', height: '35px;', src: 'http://placehold.it/35x35' }
`image_tag`使いましょう！

2017-12-30 13:17 UTC, ebkn12 commented on app/views/top/index.html.haml
> += render 'shered/header'
👍

2017-12-31 06:36 UTC, Ryosuke12323 commented on app/assets/images/chat.svg
> +</svg>
いい感じのアイコン見つけておきますね！

2017-12-31 06:51 UTC, Ryosuke12323 commented on app/assets/javascripts/application.js
> +//= require vendor/bootstrap-material-design
Boostnoteの追加しました!

2017-12-31 07:12 UTC, Ryosuke12323 commented on config/routes.rb
> +  root "top#index"
一応修正しました！

2017-12-31 07:30 UTC, Ryosuke12323 commented on app/views/top/index.html.haml
> +          %img.rounded-circle{ width: '35px;', height: '35px;', src: 'http://placehold.it/35x35' }
doneです。ついでにiconの画像変更しました。

2017-12-31 07:32 UTC, Ryosuke12323 commented on spec/controllers/top_controller_spec.rb
> +end
消しました。

2017-12-31 08:00 UTC, ebkn12 commented on app/assets/stylesheets/application.scss
> +@import 'vendor/bootstrap-material-design';
👍

2017-12-31 08:00 UTC, ebkn12 commented on app/assets/stylesheets/partials/bootstrap-custom.scss
> +      color: #424242;
インデント修正してください

2017-12-31 08:04 UTC, ebkn approved these changes
OKです！お疲れ様でした！

2018-01-10 07:22 UTC, k-kohey approved these changes

2018-01-10 09:06 UTC, merged